"""add signal grade to gas snapshots

Revision ID: 1cd7803cd96a
Revises: fd764d3322c0
Create Date: 2026-03-16 03:15:09.972160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd7803cd96a'
down_revision: Union[str, None] = 'fd764d3322c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_snapshots', sa.Column('signal_grade', sa.String(length=10), nullable=True))
    op.add_column('gas_snapshots', sa.Column('signal_grade_score', sa.Integer(), nullable=True))
    op.add_column('gas_snapshots', sa.Column('signal_tradeable', sa.Boolean(), nullable=True))
    # sa.Column('signal_tradeable', sa.Boolean(), nullable=True) -> use sa.Boolean
    op.add_column('gas_snapshots', sa.Column('signal_grade_desc', sa.String(length=255), nullable=True))
    op.add_column('gas_snapshots', sa.Column('signal_grade_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_snapshots', 'signal_grade_reasons')
    op.drop_column('gas_snapshots', 'signal_grade_desc')
    op.drop_column('gas_snapshots', 'signal_tradeable')
    op.drop_column('gas_snapshots', 'signal_grade_score')
    op.drop_column('gas_snapshots', 'signal_grade')
    # ### end Alembic commands ###
