"""add_default_symbol_risk_profile_to_users

Revision ID: 32f8ce620e7b
Revises: 446612e4c98b
Create Date: 2026-03-22 19:11:59.450875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f8ce620e7b'
down_revision: Union[str, None] = '446612e4c98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
