"""add_default_symbol_risk_profile_to_users

Revision ID: 42862909e9cc
Revises: 32f8ce620e7b
Create Date: 2026-03-22 21:18:20.489736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42862909e9cc'
down_revision: Union[str, None] = '32f8ce620e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
