"""add_default_symbol_to_users

Revision ID: 446612e4c98b
Revises: v6_001_model_drift_alerts
Create Date: 2026-03-22 18:45:53.948162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446612e4c98b'
down_revision: Union[str, None] = 'v6_001_model_drift_alerts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bulk_job_runs_id'), 'bulk_job_runs', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_job_runs_symbol'), 'bulk_job_runs', ['symbol'], unique=False)
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_model_drift_alerts_id'), 'model_drift_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.add_column('portfolios', sa.Column('strategy_tag', sa.String(length=32), nullable=True))
    op.add_column('portfolios', sa.Column('risk_tolerance', sa.String(length=16), nullable=True))
    op.add_column('portfolios', sa.Column('base_currency', sa.String(length=8), nullable=True))
    op.add_column('portfolios', sa.Column('horizon', sa.String(length=16), nullable=True))
    op.add_column('portfolios', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('portfolios', sa.Column('target_return', sa.Float(), nullable=True))
    op.add_column('portfolios', sa.Column('benchmark', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tickers_universe_id'), 'tickers_universe', ['id'], unique=False)
    op.add_column('users', sa.Column('default_symbol', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('risk_profile', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'risk_profile')
    op.drop_column('users', 'default_symbol')
    op.drop_index(op.f('ix_tickers_universe_id'), table_name='tickers_universe')
    op.drop_column('portfolios', 'benchmark')
    op.drop_column('portfolios', 'target_return')
    op.drop_column('portfolios', 'notes')
    op.drop_column('portfolios', 'horizon')
    op.drop_column('portfolios', 'base_currency')
    op.drop_column('portfolios', 'risk_tolerance')
    op.drop_column('portfolios', 'strategy_tag')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_model_drift_alerts_id'), table_name='model_drift_alerts')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_bulk_job_runs_symbol'), table_name='bulk_job_runs')
    op.drop_index(op.f('ix_bulk_job_runs_id'), table_name='bulk_job_runs')
    # ### end Alembic commands ###
