"""Initial migration

Revision ID: dfbb46c468f5
Revises: 
Create Date: 2026-03-02 01:30:36.005525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbb46c468f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name', 'date', name='_indicator_date_uc')
    )
    op.create_index(op.f('ix_macro_indicators_date'), 'macro_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_macro_indicators_id'), 'macro_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_macro_indicators_indicator_name'), 'macro_indicators', ['indicator_name'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('sentiment_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'source_type', name='_symbol_date_source_uc')
    )
    op.create_index(op.f('ix_sentiment_aggregates_date'), 'sentiment_aggregates', ['date'], unique=False)
    op.create_index(op.f('ix_sentiment_aggregates_id'), 'sentiment_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_aggregates_symbol'), 'sentiment_aggregates', ['symbol'], unique=False)
    op.create_table('stock_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='_symbol_timestamp_uc')
    )
    op.create_index(op.f('ix_stock_ohlcv_id'), 'stock_ohlcv', ['id'], unique=False)
    op.create_index(op.f('ix_stock_ohlcv_symbol'), 'stock_ohlcv', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_ohlcv_timestamp'), 'stock_ohlcv', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_ohlcv_timestamp'), table_name='stock_ohlcv')
    op.drop_index(op.f('ix_stock_ohlcv_symbol'), table_name='stock_ohlcv')
    op.drop_index(op.f('ix_stock_ohlcv_id'), table_name='stock_ohlcv')
    op.drop_table('stock_ohlcv')
    op.drop_index(op.f('ix_sentiment_aggregates_symbol'), table_name='sentiment_aggregates')
    op.drop_index(op.f('ix_sentiment_aggregates_id'), table_name='sentiment_aggregates')
    op.drop_index(op.f('ix_sentiment_aggregates_date'), table_name='sentiment_aggregates')
    op.drop_table('sentiment_aggregates')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_macro_indicators_indicator_name'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_id'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_date'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    # ### end Alembic commands ###
