import Link from "next/link";

export const metadata = {
    title: "Risk Disclaimer – Fin-Eye",
    description: "Important risk disclaimer for Fin-Eye users",
};

export default function DisclaimerPage() {
    return (
        <div className="mx-auto max-w-3xl space-y-8 py-8 text-slate-300">
            <div>
                <h1 className="text-3xl font-bold tracking-tight text-slate-50">Risk Disclaimer</h1>
                <p className="mt-2 text-sm text-slate-500">Version 1.0.0 · Effective March 2026</p>
            </div>

            <div className="rounded-xl border border-red-500/30 bg-red-950/15 p-5">
                <p className="text-base font-semibold text-red-300">
                    ⚠️ Please read this disclaimer carefully before using Fin-Eye.
                </p>
                <p className="mt-2 text-sm text-red-200/80">
                    Fin-Eye is an educational analytics platform. It does not provide investment advice.
                    Trading and investing involve risk of significant financial loss. Past performance is
                    not indicative of future results.
                </p>
            </div>

            <Section title="Not Investment Advice">
                Nothing on this platform — including Global Alignment Scores, regime classifications,
                sentiment scores, macro dashboards, backtest results, or any other signal — constitutes
                investment advice, a recommendation to buy or sell any security, or a solicitation to
                engage in any investment activity. Fin-Eye is an educational tool only.
            </Section>

            <Section title="Model Limitations">
                All signals produced by Fin-Eye are generated by statistical and machine-learning models
                trained on historical market data. These models:
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
                    <li>Can and do produce incorrect predictions, especially during unusual market conditions.</li>
                    <li>Are subject to model drift — performance naturally degrades as market regimes change.</li>
                    <li>Cannot account for unknown unknowns, black-swan events, or sudden macro shocks.</li>
                    <li>May reflect biases present in historical training data.</li>
                </ul>
            </Section>

            <Section title="Backtesting Limitations">
                Backtest results shown on the platform are simulations based on historical data and are
                subject to significant limitations:
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
                    <li><strong className="text-slate-200">Look-ahead bias:</strong> Models may inadvertently use future information not available at the time of a historical trade.</li>
                    <li><strong className="text-slate-200">Survivorship bias:</strong> Historical datasets may exclude delisted or bankrupt securities.</li>
                    <li><strong className="text-slate-200">Overfitting:</strong> Strategies that perform well in backtests may have been inadvertently tuned to past data and will not replicate in live trading. Live Sharpe ratios are typically 40–60% lower than backtest Sharpe ratios.</li>
                    <li><strong className="text-slate-200">Execution assumptions:</strong> Backtests assume ideal execution. Real trading involves slippage, market impact, partial fills, and platform outages.</li>
                </ul>
            </Section>

            <Section title="Sentiment & News Analysis Limitations">
                Sentiment scores are produced by Natural Language Processing models (FinBERT) that may
                misclassify articles due to sarcasm, irony, domain-specific language, or context the model
                was not trained on. Retail sentiment data (Reddit) reflects social discussion, not
                institutional positioning, and is subject to coordinated manipulation and noise.
            </Section>

            <Section title="Macro Data Limitations">
                Macro indicators such as CPI, unemployment, and Fed Funds Rate are released with time
                lags and are subject to revision. By the time data appears on this platform, markets may
                have already priced in the information. Historical correlations between macro indicators
                and asset prices may break down during structural economic shifts.
            </Section>

            <Section title="Risk of Loss">
                Trading equities, derivatives, ETFs, and other financial instruments involves the risk of
                losing some or all of your invested capital. You should only invest money you can afford
                to lose entirely. Leveraged products amplify both gains and losses. Fin-Eye does not
                assess your personal financial situation, risk tolerance, or investment objectives.
            </Section>

            <Section title="Your Responsibility">
                You are solely responsible for all financial decisions you make. Before making any
                investment decision, you should:
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
                    <li>Conduct your own independent research.</li>
                    <li>Consult a licensed and regulated financial adviser.</li>
                    <li>Understand the risks of the specific instruments you are considering.</li>
                    <li>Consider your own financial situation, goals, and risk tolerance.</li>
                    <li>Never trade based solely on a single signal, score, or automated recommendation.</li>
                </ul>
            </Section>

            <Section title="No Liability">
                Fin-Eye and its operators accept no responsibility or liability for:
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
                    <li>Any financial losses incurred as a result of using this platform.</li>
                    <li>Inaccuracies or delays in third-party data sources (FRED, Yahoo Finance, Finnhub, Reddit).</li>
                    <li>Errors, bugs, or interruptions in the platform's services.</li>
                    <li>The performance of any strategy backtested or described on the platform.</li>
                </ul>
            </Section>

            <div className="border-t border-slate-800 pt-6 flex flex-wrap gap-4 text-sm">
                <Link href="/legal/terms" className="text-blue-400 hover:text-blue-300">Terms of Service</Link>
                <Link href="/legal/privacy" className="text-blue-400 hover:text-blue-300">Privacy Policy</Link>
                <Link href="/" className="text-slate-500 hover:text-slate-400">← Back to App</Link>
            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="space-y-2">
            <h2 className="text-lg font-semibold text-slate-100">{title}</h2>
            <div className="text-sm leading-relaxed text-slate-400">{children}</div>
        </section>
    );
}
